### ISSUE TITLE
Ruby example for reliable exception management with customer message?

### ISSUE THREAD

**Issue by thbar** [recurly/recurly-js-examples#10]
The ruby example gives [this](https://github.com/recurly/recurly-js-examples/blob/master/api/ruby/app.rb#L35) for error checking:

``` ruby
rescue Recurly::Resource::Invalid, Recurly::API::ResponseError => e
    # Here we may wish to log the API error and send the
    # customer to an appropriate URL, perhaps including
    # and error message
    puts e
    redirect 'ERROR_URL'
  end
```

Empirically, I came up with this (without looking too much at the gem source code for now):

``` ruby
  def build_customer_facing_error_message(exception)
    # this seems to work, empirically, for some subclasses from ResponseError
    message = exception.try(:transaction).try(:transaction_error).try(:[], 'customer_message')
    message || "An error occurred!"
  end
```

Is there a recommended way to extract the customer message? Thanks!

**Comment by thbar** [comment]
I found a way to handle more cases, without risk of leaking non-customer-facing data, that will still handle declines as well as "duplicate subscriptions" like in Recurly.js v2.

This is a bit ugly:

```ruby
  def build_customer_facing_error_message(exception)
    default_message = "An error occurred!"
    message = case exception
      when Recurly::Transaction::DeclinedError
        exception.message
      when Recurly::Resource::Invalid
        # not sure how to form a reliable message here yet
        content = exception.record.errors.values.map(&:to_s).join(', ')
        # handle at least this case
        if content =~ /already have a subscription/
          'You already have a subscription to this plan.'
        else
          # TODO: build a more meaningful message, but only with something
          # valid for customer facing
          default_message
        end
      when Recurly::API::ResponseError
        exception.transaction.transaction_error['customer_message']
    end
    message || default_message
  rescue
    # return something in all cases, eg a nil field etc
    default_message
  end
```

I'll try to improve that, but if you have a bit of guidance, this is most welcome :-)

**Comment by thbar** [comment]
So far I see different advice given in different places:

-  the sample tells to catch `Recurly::Resource::Invalid` and `Recurly::API::ResponseError`
- the library doc (embedded) seems to indicate to catch `Recurly::Transaction::DeclinedError` and others
- the [site](https://docs.recurly.com/client-libraries/ruby) tells to catch `Recurly::Resource::NotFound` and `Recurly::API::UnprocessableEntity`

So while my snippet above seems to work, I'm a bit confused at this point!

**Comment by jvenezia** [comment]
Would be nice to have an official guide from recurly for this.

**Comment by bennadel** [comment]
Agreed - I'm finding it very difficult to find reliable information on error handling and possible error messages. Specifically "validation" errors, not transaction errors.
