### ISSUE TITLE
Demo still uses Recurly.js v3

### ISSUE THREAD

**Issue by forevermatt** [recurly/recurly-js-examples#25]
In the README.md file, the source code provided for [the "Minimal billing information" example](https://github.com/recurly/recurly-js-examples/blob/master/public/minimal) shows how to use Recurly.js v4, but [the Demo](https://kale-krate.herokuapp.com/subscribe-minimal) is still using the older Recurly.js v3.

**Comment by tommoor** [comment]
This demo is now totally offline
