### ISSUE TITLE
Demo is offline

### ISSUE THREAD

**Issue by Anto59290** [recurly/recurly-js-examples#28]
The link given for demo in the readme file is offline : 
https://kale-krate.herokuapp.com/subscribe-minimal

**Comment by Anto59290** [comment]
Any news on this ?

**Comment by chrissrogers** [comment]
Removed in https://github.com/recurly/recurly-js-examples/commit/197b10b497306b86ed5060d70f5caaff3f86ec78#diff-04c6e90faac2675aa89e2176d2eec7d8
