### ISSUE TITLE
Paypal normal flow example

### ISSUE THREAD

**Issue by Paragonid** [recurly/recurly-js-examples#31]
Please add or link Paypal normal flow example

**Comment by Paragonid** [comment]
As far as I understand I can use token returned by Paypal and then proceed to [Update Account's Billing Info (using external token)](https://dev.recurly.com/v2.7/docs/update-an-accounts-billing-info-using-external-token). Is it correct?

It's confusing that `first_name` is set to `required`. Don't see why is it important in this request

**Comment by chrissrogers** [comment]
@Paragonid my apologies for not seeing your question here. I;ll answer this here in case anyone has a similar question.

The docs you linked to are correct, that's what you would be using to submit a paypal token. `first_name` is a requirement for all of our `billing_info` requests.
