### ISSUE TITLE
Recurly.js v4 slowed by other (third-party) scripts on page

### ISSUE THREAD

**Issue by hkmaly** [recurly/recurly-js-examples#35]
Hello,

I noticed that recurly v4 is visibly slower if other (third-party) scripts on page, like social media widgets (facebook, twitter) or analytics (google analytics) takes too long. Any ideas how to make analytics and/or twitter wait for recurly instead of recurly wait for analytics and/or twitter?

(Note: Hard to reproduce, as usually the analytics is not so slow ... but I would prefer to ensure good behaviour always.)

**Comment by chrissrogers** [comment]
I'd suggest analyzing your page loads using chrome developer tools to see if there is a clear blocking order. Structurally, I'd also suggest loading recurly.js on your page before other third party scripts, as its initialization is fast compared to other scripts which may need to make network requests when they initialize.

There is a `recurly.ready` method which will answer a callback once recurly.js has finished initializing after a `configure` call, at which time you could load other third party scripts. But I'd suggest the load order change first.
